CC = g++
CPP_FILES = main.cpp
EXT_PATH = ../gm-project/extensions/
ifeq ($(OS), Windows_NT)
	EXT=dll
else
	EXT=so
endif

build:
	echo "Build STUB -- C++ libraries not yet implemented"
#	$(CC) -std=c++20 -shared -Wall -fpic $(CPP_FILES) -o ./bin/[LIBRARY_NAME].$(EXT) -lpthread
#	Should build files into local bin folder 

install:
	echo "Install STUB -- C++ libraries not yet implemented"
#	Should copy files from build folder into extensions folder
